### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by Yomguithereal** [glenjamin/devcards-js#13]
Should we plan to display a menu with the available namespaces so we can choose one and directly showing a namespace only if there is only one loaded?

**Comment by glenjamin** [comment]
Yep, this is something I want to do, along with clickable card titles for single-card focus.

**Comment by Yomguithereal** [comment]
Then this is probably a reason why [this](https://github.com/glenjamin/devcards-js/blob/master/devcards.js#L12-L14) has to stay.

Just a little question: does `react-router` seems overkill to you for this job?

**Comment by glenjamin** [comment]
Yeah, it might be a bit heavy. I've heard their history lib is pretty good though.

**Comment by Yomguithereal** [comment]
Yes, the history lib is good. Thing is with just history we'll have to reinvent the wheel by doing pattern matching etc. and binding our components to the URL etc. Should we try a lighter option like the ones displayed [here](http://microjs.com/#router)?

**Comment by glenjamin** [comment]
Since we'd basically be generating every URL from the card names, we might be able to just do string matching.

I've used https://www.npmjs.com/package/routes in the past and been pretty happy with it.

**Comment by Yomguithereal** [comment]
Ok. Should we handle routing in the `Devcards` component with local state for convenience? Or do we try better?

**Comment by Yomguithereal** [comment]
Maybe create a `DevcardLayout` component for instance.

**Comment by glenjamin** [comment]
In the current setup, I think `<Devcards>` is the easiest place.

It might make more sense to arrange as:

```
<DevCards>
  <DevCardNamespace>
    <DevCard>
```

**Comment by Yomguithereal** [comment]
Do we agree that `routes` only perform pattern matching etc. and we need to use the history lib alongside?

**Comment by glenjamin** [comment]
Yup, happy to consider alternate solutions as well.

**Comment by Yomguithereal** [comment]
Maintainer of routes links to other similar libraries that are still maintained. I'll check them and make a proposition through a PR this afternoon if I find some time.

**Comment by glenjamin** [comment]
One of the goals I had jotted down in my list was
>  ID for each card which can be linked to, like headings in github readmes

I had thought about this as being able to link to scrolling to a named part of the card page.

Any ideas how to provide the ability to focus on one card at a time, but also to do this?

**Comment by Yomguithereal** [comment]
* specialized routing: `/focus/:card`, `/goto/:card.
* Using the query.
* Append something to the route

**Comment by glenjamin** [comment]
Appending could work actually,

* /:ns/:card
* /:ns/:card/focus

**Comment by Yomguithereal** [comment]
We should check what libraries like angular etc. and backbone router does to handle things that should be interpreted by the browser as a classical hash (id typically) when using some routing on top of it.

**Comment by glenjamin** [comment]
As far as I know they don't - they use additional scrollTo calls when necessary

**Comment by Yomguithereal** [comment]
We could also use HTML5 routing without hashes so we can keep using hashes to refer ids.

**Comment by glenjamin** [comment]
I considered that, but it would force server-side routing to work to allow refreshing the page.

At the moment everything still works the same if you run from static HTML on a demo site.


Client side routing and fragment identifiers don't "just work" anyway, because the browser tries to scroll before the new page has rendered.

**Comment by glenjamin** [comment]
I've just pushed some stuff to allow `focus` as well as linking to a card in a namespace.

I think we can call routing done now.
