### ISSUE TITLE
Syntax highlight

### ISSUE THREAD

**Issue by Yomguithereal** [glenjamin/devcards-js#19]
Hello @glenjamin. I have just opened a [PR](https://github.com/rexxars/commonmark-react-renderer) concerning custom rendering logic for `commonmark-react-renderer`. If this is merged, we could easily render code blocks using [highlight.js](https://highlightjs.org/).

Would this do the job?

**Comment by glenjamin** [comment]
I think that'll work - we probably don't actually need the custom renderer - can just apply highlight.js in componentDidMount/Update on any code tags.

We'll still need a pretty-printer for objects, and/or an expando/collapse thing for large objects

**Comment by Yomguithereal** [comment]
Yes we could perform highlight on lifecycle methods but this is less elegant and still relies on the DOM.

> We'll still need a pretty-printer for objects, and/or an expando/collapse thing for large objects.

Does one of the solutions listed in #6 seem to stand out?

**Comment by glenjamin** [comment]
Calling this done for now - fancier object pretty-printing is a different matter.
