### ISSUE TITLE
The `focus` part in the breadcrumb seems to remain more than necessary

### ISSUE THREAD

**Issue by Yomguithereal** [glenjamin/devcards-js#21]

**Comment by glenjamin** [comment]
Got some steps to reproduce?

The card name is always a link to focus, the anchor appears next to it when hovering.

**Comment by Yomguithereal** [comment]
1. Click on "API Walkthrough"
2. Click on "A devcard"
3. Click on "Devcards" in breadcrumbs
4. Watch breadcrumbs.

**Comment by glenjamin** [comment]
Oh, so it does. That's new - it wasn't doing that earlier!

**Comment by glenjamin** [comment]
Ah yes, I'd just never clicked back to the index!

Fixed in 64170ae
