### ISSUE TITLE
Code fence margins

### ISSUE THREAD

**Issue by Yomguithereal** [glenjamin/devcards-js#24]
Code fence margins are not constant and this result in strange visual things on the API Walkthrough.

**Comment by glenjamin** [comment]
Is this what you're seeing?

<img width="1009" alt="screen shot 2016-02-02 at 10 05 27" src="https://cloud.githubusercontent.com/assets/151272/12746026/869949a6-c994-11e5-92ab-3be3d3ae947b.png">

**Comment by Yomguithereal** [comment]
Yes. Top and bottom margins are not the same. But it's probably more problematic below.

**Comment by glenjamin** [comment]
Ah, I see what you mean - I thought you were referring to the left/right margins

**Comment by glenjamin** [comment]
Fixed in 55c4183
