### ISSUE TITLE
White background

### ISSUE THREAD

**Issue by Yomguithereal** [glenjamin/devcards-js#25]
I am pondering whether the cards container should really enforce a white background. (Note within the card body but really the whole cards list container).

**Comment by glenjamin** [comment]
I agree the container shouldn't, only the cards themselves.

**Comment by glenjamin** [comment]
Although I'm not totally against making it hard to style stuff that isn't the body of cards - as it might help people focus on making the cards themselves.

**Comment by glenjamin** [comment]
Fixed this in a521f7e - I think

**Comment by glenjamin** [comment]
Does this now do what you expected @Yomguithereal ?

Happy to close?

**Comment by Yomguithereal** [comment]
I thinks it's fine now. Need to test on an app but I'll trust you :)
