### ISSUE TITLE
Helpers checking body type

### ISSUE THREAD

**Issue by Yomguithereal** [glenjamin/devcards-js#26]
Hello @glenjamin. Why [those](https://github.com/glenjamin/devcards-js/blob/master/lib/components/Body.js#L19-L29) helpers? Isn't `instanceof` enough?

```js
body instanceof RegExp
body instanceof Date
```

**Comment by glenjamin** [comment]
For roughly the same reason `Array.isArray` exists, in case the values comes from a different root context.

Iframes can do this, and I think also web workers?

**Comment by glenjamin** [comment]
Going to replace these with
* https://www.npmjs.com/package/is-date-object
* https://www.npmjs.com/package/is-regexp

**Comment by glenjamin** [comment]
Fixed in bb97dc8
