### ISSUE TITLE
Node.js util.inspect

### ISSUE THREAD

**Issue by Yomguithereal** [glenjamin/devcards-js#28]
Just had and idea so we can easily process Sets and Maps etc. for display. Why not use node's util.inspect? It works quite well, recursively also, and is injected by webpack for browser usage.

**Comment by Yomguithereal** [comment]
Plus it will work with Immutable.js since their objects implement the .inspect method.

**Comment by glenjamin** [comment]
Sounds sensible, I'd like to keep webpack as optional, but we can use https://github.com/defunctzombie/node-util directly.

**Comment by Yomguithereal** [comment]
Just a little problem though :). This module hasn't been updated to comply with latest Node v4 & v5 version and does not display ES2015 objects neatly.

**Comment by glenjamin** [comment]
Ah, do you know which shim webpack uses?

**Comment by Yomguithereal** [comment]
This very module.

**Comment by Yomguithereal** [comment]
Solutions are:

1. I get involved with the module and try a PR.
2. We use node.js' [sources](https://github.com/nodejs/node/blob/master/lib/util.js#L87) themselves.

**Comment by glenjamin** [comment]
The node sources have a lot of stuff that would only work on node itself - using native checks for types

**Comment by glenjamin** [comment]
https://github.com/Xotic750/inspect-x appears to be very comprehensive

**Comment by Yomguithereal** [comment]
Good catch. Let's try if this work. If this correctly implement object.inspect it could work. Let's try it!

**Comment by glenjamin** [comment]
Going to give it a go right now, looks like it might cover almost all the cases we care about

**Comment by glenjamin** [comment]
Hit an issue https://github.com/Xotic750/inspect-x/issues/43

**Comment by Yomguithereal** [comment]
It seems we are the victims of quite a persistent curse.

**Comment by glenjamin** [comment]
Fixed in 2fe720e73023410500d90242ac06d18025461036
