### ISSUE TITLE
Rendered markdown doc triggers a React warning about keys

### ISSUE THREAD

**Issue by Yomguithereal** [glenjamin/devcards-js#3]
Related issue [here](https://github.com/rexxars/commonmark-react-renderer/issues/3) on `react-commonmark-renderer`.

**Comment by glenjamin** [comment]
This still seems to be happening with `react-commonmark-renderer@2.2.2` - can be seen on http://localhost:3000/#/API%20Walkthrough

**Comment by Yomguithereal** [comment]
That's quite strange. I should check the output of the renderer once more. It seems to produce a lot of spans for nothing.

**Comment by glenjamin** [comment]
Resolved in 481acbc2615fdbf82dbd450bde0dea6bb68752f8

**Comment by Yomguithereal** [comment]
I worked on this issue on the library but I think the fix will land in an ulterior version.

**Comment by glenjamin** [comment]
Seems to be fixed in 4.0.1 as mentioned in https://github.com/rexxars/commonmark-react-renderer/pull/11#issuecomment-186925848
