### ISSUE TITLE
Friendly display of JS datatypes

### ISSUE THREAD

**Issue by Yomguithereal** [glenjamin/devcards-js#6]
The [`react-object-inspector`](https://www.npmjs.com/package/react-object-inspector) is quite straightforward and we could probably use it to display JS data the way the clojure's implementation does.

**Comment by glenjamin** [comment]
Looks ace, I'll convert the checklist task to separate issues and add some suggestions where I have ideas.

**Comment by glenjamin** [comment]
Other options:

* https://github.com/Lapple/react-json-inspector
* https://github.com/chibicode/react-json-tree (used by redux devtools)

**Comment by glenjamin** [comment]
* I'd like to be able to show Immutable-js objects as clearly immutable objects.
* I'd like to show small objects fully expanded by default
* I'd like to syntax highlight

**Comment by Yomguithereal** [comment]
I guess that for syntax highlight we should help `commonmark-react-renderer` to do so. I recall it was on their roadmap.

**Comment by Yomguithereal** [comment]
Should we use highlight.js?

**Comment by glenjamin** [comment]
https://www.npmjs.com/package/json-stringify-pretty-compact + highlight looks like a good first approach, rather than going straight in with the fancy ones

**Comment by Yomguithereal** [comment]
If you don't mind having a git dependency for `commonmark-react-renderer` for a little while, I can try to add syntax highlight and implement you approach above for datatypes display tomorrow.

**Comment by glenjamin** [comment]
That would be great, is the idea that the <code> component would be customised to apply highlight JS stuff?

You can always publish a fork to npm under a slightly different name.

**Comment by glenjamin** [comment]
Closing this, might revisit a fancy collapsible display at a later date.
