### ISSUE TITLE
Suggested defcard API

### ISSUE THREAD

**Issue by glenjamin** [glenjamin/devcards-js#7]
Attempt to get pretty close to http://rigsomelight.com/devcards/#!/devdemos.defcard_api
Rather than have `initial-state` as a top-level arg, I think it'll be easier to treat it as an option.

* `name` is a short string
* `doc` is a string that is parsed as markdown
* `body` can be many different things, when it's a string it renders like `doc`.
* `options` an options object 

```js
defcard(body);
defcard(name, body);
defcard(name, doc, body);
defcard(name, body, options);
defcard(name, doc, body, options);

// same overloads as above, doesn't render anything
defcard.off()

// cards without names
defcard.anon(body); // same as defcard(body)
defcard.anon(doc, body); // if arg1 is a string
defcard.anon(body, options); // if arg1 is not a string
defcard.anon(doc, body, options);
```

**Comment by Yomguithereal** [comment]
I think you can add `defcard(body, options)`.

**Comment by glenjamin** [comment]
> I think you can add `defcard(body, options).`

To do that the logic would have to be "if arg1 is not a string", that means you wouldn't be able to do `defcard(doc, options)`. That's probably ok though, as you can still do `defcard.anon(doc, options)`

**Comment by glenjamin** [comment]
I've just pushed XXX which I think does the most number of combinations that is possible

It looks like this

```
  devcard()
    ✓ accepts devcard(doc)
    ✓ accepts devcard(body)
    ✓ accepts devcard(name, body)
    ✓ accepts devcard(name, doc)
    ✓ accepts devcard(name, doc, body)
    ✓ accepts devcard(name, doc, body, options)
    ✓ accepts devcard.anon(doc)
    ✓ accepts devcard.anon(body)
    ✓ accepts devcard.anon(doc, body)
    ✓ accepts devcard.anon(body, options)
    ✓ accepts devcard.anon(doc, body, options)
    ✓ ignores devcard.off(body)
    ✓ ignores devcard.off(name, doc)
    ✓ ignores devcard.off(name, doc, body)
    ✓ ignores devcard.off(name, doc, body, options)
```

Anything you think is missing?

The tricky bits are there's no way to tell the difference between `name` and `doc` or between `body` and `options` from looking at the types alone.

**Comment by Yomguithereal** [comment]
Seems quite right.
