### ISSUE TITLE
Let the card hold state

### ISSUE THREAD

**Issue by glenjamin** [glenjamin/devcards-js#8]
Something like this:

```js
defcard(
  "state demo",
  function(card) {
    return <button onClick={() => card.setState(x => x + 1)>{card.state}</button>;
  },
  { state: 123 }
)
```

Use a single argument function with properties to make future extensions easier

Like in react, `setState` should accept an object to merge, or a function to apply to the current state.

part 2: If state is an atom, it should be subscribed to and the function re-rendered whenever it changes.

**Comment by glenjamin** [comment]
Added this today in 2a3d4165c21094b5b88eda437fe22333fb2bd605

**Comment by Yomguithereal** [comment]
What does the `inspect` param stands for?

**Comment by glenjamin** [comment]
> What does the inspect param stands for?

https://github.com/glenjamin/devcards-js/commit/2a3d4165c21094b5b88eda437fe22333fb2bd605#diff-77ebb40903458615ebd2616b4ea29211R57

**Comment by Yomguithereal** [comment]
Thanks. Sounds useful indeed.
